# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CIT 480 Senior Design
email: kevin.chung.731@my.csun.edu
description: >- # this means to ignore newlines until "baseurl:"
        Cal State University, Northridge - Senior Design - Kevin Chuung
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  helloitskayc

# Build settings
#theme: minima
plugins:
  - jekyll-feed


body {
                font-family: Verdana, Geneva, times, serif;
                        font-size: 100%;
                                width: 80%;
                                        margin-right: auto;
                                                margin-left: auto;
                                                        padding: 1% 2.5% 1.5%;
                                                                background: white;
                                                                        line-height: 1.5;
                                                                          border: 5.35em double rgb(83, 104, 138);
                                                                        }

                                                                        /* h1, h2, h3, h4, h5, h6, p {
                                                                                        margin: 0;
                                                                                                padding: 0;
                                                                                        } 
                                                                                        not in use yet 
                                                                                        there are many edits woop
                                                                                        */

                                                                                        h1, h2, h3, h4, h5, h6, h7{
                                                                                                  font-family: Verdana, Geneva, times, serif;
                                                                                                    font-weight: bold;
                                                                                                        color: rgb(83, 104, 138);
                                                                                                          margin-top: 15px;
                                                                                                            margin-bottom: 10px;
                                                                                                              
                                                                                                          }

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
